import type { Metadata } from "next";
import InventoryPage from "./page";

import "@/styles/globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function InventoryLayout() {
  return (
    <main>
      <InventoryPage />
    </main>
  );
}
