import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/navigation/component";
import { CssBaseline, ThemeProvider } from "@mui/material";
import theme from "@/theme/theme";

import "@/styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          {children}
        </ThemeProvider>
        <Navigation />
      </body>
    </html>
  );
}
